version: '3'

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: search-engine
      POSTGRES_PASSWORD: search-engine
      POSTGRES_DB: search-engine
    networks:
      - network-search-engine
    ports:
      - 54321:5432

  search-engine:
    build: .
    command: ["./tools/run.sh"]
    volumes:
      - files_data:/files
    environment:
      PG_HOST: postgres
      PG_USER: search-engine
      PG_DATABASE: search-engine
      PG_PASSWORD: search-engine
    depends_on:
      - postgres
    restart: always
    networks:
      - network-search-engine
    ports:
      - 8001:8001

volumes:
  postgres_data:
  files_data:

networks:
  network-search-engine:
