version: '3'

services:
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: search-engine
      POSTGRES_PASSWORD: search-engine
      POSTGRES_DB: search-engine
    networks:
      - network-search-engine

  search-engine:
    build: .
    command: uvicorn run:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - pytorch_model:/root/.cache/torch/checkpoints
      - ${PWD}/app:/app
      - ${PWD}/core:/core
      - files_data:/files
    environment:
      PG_HOST: postgres
      PG_USER: search-engine
      PG_DATABASE: search-engine
      PG_PASSWORD: search-engine
    depends_on:
      - postgres
    restart: always
    networks:
      - network-search-engine
    ports:
      - 8001:8001

volumes:
  postgres_data:
  files_data:
  pytorch_model:

networks:
  network-search-engine:
